2021-05-21 21:13:29,957 INFO    MainThread:140418 [wandb_setup.py:_flush():69] setting env: {}
2021-05-21 21:13:29,957 INFO    MainThread:140418 [wandb_setup.py:_flush():69] setting login settings: {}
2021-05-21 21:13:29,957 INFO    MainThread:140418 [wandb_init.py:_log_setup():336] Logging user logs to /home/indika/Programming/Projects/Python/Artifical-Intelligence/PyTorch/CNN/Mask-Detection-PT-V2/wandb/run-20210521_211329-pkf6twxa/logs/debug.log
2021-05-21 21:13:29,957 INFO    MainThread:140418 [wandb_init.py:_log_setup():337] Logging internal logs to /home/indika/Programming/Projects/Python/Artifical-Intelligence/PyTorch/CNN/Mask-Detection-PT-V2/wandb/run-20210521_211329-pkf6twxa/logs/debug-internal.log
2021-05-21 21:13:29,958 INFO    MainThread:140418 [wandb_init.py:init():369] calling init triggers
2021-05-21 21:13:29,958 INFO    MainThread:140418 [wandb_init.py:init():376] wandb.init called with sweep_config: {}
config: {}
2021-05-21 21:13:29,958 INFO    MainThread:140418 [wandb_init.py:init():391] re-initializing run, found existing run on stack: 33yzuww7
2021-05-21 21:13:29,959 INFO    MainThread:140418 [wandb_run.py:finish():1208] finishing run ranuga-d/Face-Mask-Detection-PT-V2/33yzuww7
2021-05-21 21:13:29,975 INFO    MainThread:140418 [jupyter.py:save_history():349] saving 55 cells to _session_history.ipynb
2021-05-21 21:13:29,992 INFO    MainThread:140418 [wandb_run.py:_config_callback():787] config_cb ('_wandb', 'session_history') code/_session_history.ipynb None
2021-05-21 21:13:30,077 INFO    MainThread:140418 [jupyter.py:save_ipynb():268] looking for notebook: train.ipynb
2021-05-21 21:13:30,685 INFO    MainThread:140418 [wandb_init.py:_jupyter_teardown():267] saved code and history
2021-05-21 21:13:30,685 INFO    MainThread:140418 [wandb_init.py:_jupyter_teardown():268] cleaning up jupyter logic
2021-05-21 21:13:30,685 INFO    MainThread:140418 [wandb_run.py:_atexit_cleanup():1535] got exitcode: 0
2021-05-21 21:13:30,685 INFO    MainThread:140418 [wandb_run.py:_restore():1507] restore
2021-05-21 21:13:32,012 INFO    MainThread:140418 [wandb_init.py:init():418] starting backend
2021-05-21 21:13:32,013 INFO    MainThread:140418 [backend.py:_multiprocessing_setup():72] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2021-05-21 21:13:32,015 INFO    MainThread:140418 [backend.py:ensure_launched():132] starting backend process...
2021-05-21 21:13:32,046 INFO    MainThread:140418 [backend.py:ensure_launched():137] started backend process with pid: 180076
2021-05-21 21:13:32,047 INFO    MainThread:140418 [wandb_init.py:init():423] backend started and connected
2021-05-21 21:13:32,057 INFO    MainThread:140418 [wandb_init.py:init():465] updated telemetry
2021-05-21 21:13:32,057 INFO    MainThread:140418 [wandb_init.py:init():484] communicating current version
2021-05-21 21:13:33,252 INFO    MainThread:140418 [wandb_init.py:init():489] got version response 
2021-05-21 21:13:33,252 INFO    MainThread:140418 [wandb_init.py:init():497] communicating run to backend with 30 second timeout
2021-05-21 21:13:34,078 INFO    MainThread:140418 [wandb_init.py:init():522] starting run threads in backend
